server_1: asynchronous_network.cc main_1.cc log_file.cc paxos_log.cc replicated_log.cc paxos.cc utils.cc results_buffer.cc
	g++ -o asynchronous_network.o -c asynchronous_network.cc
	g++ -o main_1.o -c main_1.cc
	g++ -o log_file.o -c log_file.cc
	g++ -o paxos_log.o -c paxos_log.cc
	g++ -o replicated_log.o -c replicated_log.cc
	g++ -o paxos.o -c paxos.cc
	g++ -o utils.o -c utils.cc
	g++ -o results_buffer.o -c results_buffer.cc
	g++ -o server_1 asynchronous_network.o main_1.o log_file.o paxos_log.o replicated_log.o paxos.o utils.o results_buffer.o -lpthread

server_2: asynchronous_network.cc main_2.cc log_file_1.cc paxos_log_1.cc replicated_log.cc paxos.cc utils.cc results_buffer.cc
	g++ -o asynchronous_network.o -c asynchronous_network.cc
	g++ -o main_2.o -c main_2.cc
	g++ -o log_file_1.o -c log_file_1.cc
	g++ -o paxos_log_1.o -c paxos_log_1.cc
	g++ -o replicated_log.o -c replicated_log.cc
	g++ -o paxos.o -c paxos.cc
	g++ -o utils.o -c utils.cc
	g++ -o results_buffer.o -c results_buffer.cc
	g++ -o server_2 asynchronous_network.o main_2.o log_file_1.o paxos_log_1.o replicated_log.o paxos.o utils.o results_buffer.o -lpthread

server_3: asynchronous_network.cc main_3.cc log_file_1.cc paxos_log_1.cc replicated_log.cc paxos.cc utils.cc results_buffer.cc
	g++ -o asynchronous_network.o -c asynchronous_network.cc
	g++ -o main_3.o -c main_3.cc
	g++ -o log_file_1.o -c log_file_1.cc
	g++ -o paxos_log_1.o -c paxos_log_1.cc
	g++ -o replicated_log.o -c replicated_log.cc
	g++ -o paxos.o -c paxos.cc
	g++ -o utils.o -c utils.cc
	g++ -o results_buffer.o -c results_buffer.cc
	g++ -o server_3 asynchronous_network.o main_3.o log_file_1.o paxos_log_1.o replicated_log.o paxos.o utils.o results_buffer.o -lpthread

server_4: asynchronous_network.cc main_4.cc log_file_1.cc paxos_log_1.cc replicated_log.cc paxos.cc utils.cc results_buffer.cc
	g++ -o asynchronous_network.o -c asynchronous_network.cc
	g++ -o main_4.o -c main_4.cc
	g++ -o log_file_1.o -c log_file_1.cc
	g++ -o paxos_log_1.o -c paxos_log_1.cc
	g++ -o replicated_log.o -c replicated_log.cc
	g++ -o paxos.o -c paxos.cc
	g++ -o utils.o -c utils.cc
	g++ -o results_buffer.o -c results_buffer.cc
	g++ -o server_4 asynchronous_network.o main_4.o log_file_1.o paxos_log_1.o replicated_log.o paxos.o utils.o results_buffer.o -lpthread


